name: flowscope
version: "1.0.0"
config-version: 2
profile: flowscope

model-paths: ["models"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  flowscope:
    silver:
      +schema: silver
      +materialized: table
    gold:
      +schema: gold
      +materialized: table
